# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e84de846816333b7de33064f6fc0defcdee5474c4e750a35d6c026df8e8293fbd6727d1498b6fc85a21f00d632ea0ce698be1129799de79a1000572fe62c2be9

test:
  secret_key_base: 165cef670c82b96ec0495a8c975672e52e8b09e930004c62451bf11b1fc0b50033d55b888d714607b68f33d7da8d296233b79fdb39b4fddd185e0f8e84dd4224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
